[[MirroredArrays]]
git-tree-sha1 = "412a32947ae4f599e5a3422c7b8fff4167e8504f"
repo-rev = "master"
repo-url = "https://github.com/slmcbane/MirroredArrays.jl"
uuid = "edfed022-ddf0-11e8-3461-e736d26fdb96"
version = "0.2.0"
