[[MirroredArrays]]
git-tree-sha1 = "1f9cbf34a8cd666cc40cff9f5a1f2594e01bf5f4"
repo-rev = "master"
repo-url = "https://github.com/slmcbane/MirroredArrays.jl"
uuid = "edfed022-ddf0-11e8-3461-e736d26fdb96"
version = "0.1.0"
